version: '3.3'

networks:
    laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes: 
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "6080:80"
    depends_on: 
      - php
      - mysql
    networks:
      - laravel


  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports: 
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: zen
      MYSQL_USER: root    
      MYSQL_PASSWORD: Password@123
      MYSQL_ROOT_PASSWORD: Password@123
    
    networks:
      - laravel

    
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes: 
      - ./src:/var/www/html/
    ports: 
      - "9000:9000"

    networks:
      - laravel


